### ISSUE TITLE
Release notes / change log?

### ISSUE THREAD

**Issue by ledbettj** [team-telnyx/telnyx-ruby#43]
I have been running version `0.0.8` in production.  Recently I noticed that there's a version `0.1.0` available via ruby gems.  However, the code in this repo in `lib/telnyx/version.rb` and `VERSION` are still marked `0.0.1` and there are no releases or tags that I can find that point to the version(s) released on rubygems.

How can I tell if it's safe to upgrade?  Are the changes or release notes available somewhere? Or is there anywhere I can at least do a `git diff` between the versions?

Cheers!

**Comment by eoghantelnyx** [comment]
Hey @ledbettj, thanks for creating the issue. We have incorporated releases and version maintenance into our publishing process. You were ahead of your time as the version was bumped wrongly on the most recent release by myself to v2.2.0 from v0.1.0
I added a release for the most recent SDK publish: https://github.com/team-telnyx/telnyx-ruby/releases/tag/v2.2.0
