### ISSUE TITLE
Update SDK to be on parity with openapi spec (Bounty)

### ISSUE THREAD

**Issue by ADandyGuyInSpace** [team-telnyx/telnyx-ruby#86]
Telnyx openapi spec file located here: https://github.com/team-telnyx/openapi/blob/master/openapi/spec3.json

We need to update this SDK to include the missing endpoints. These are the documented endpoints that are done and the ones that need to be done: https://docs.google.com/spreadsheets/d/1jVdMd1S5z9pdFwB1wV8-GFhRfJ6dAitsUtwqS1Q9cm4/edit?usp=sharing

Feel free to ask for access and will share. Should be straightforward, following same guidelines and adding tests as you go on. Use old endpoints as reference.

**Comment by vionash** [comment]
There is a bounty for this issue if you want to contribute: https://gitpay.me/#/task/714/update-sdk-to-be-on-parity-with-openapi-spec

**Comment by GildedHonour** [comment]
If it's a bountry, I'd take it

Ruby, Python at least
Perhaps .NET too
@vionash

**Comment by mnyon-grandkru** [comment]
@ADandyGuyInSpace How can I gain access to the drive doc? Thanks.

**Comment by ADandyGuyInSpace** [comment]
Closed, updated repo
